version: '3.2'
services:
  mongo:
    image: mongo:4.2 #Use arm64v8/mongo for raspberry pi 4(aarch64)
    container_name: mongo
    ports:
      - 27017:27017
    # volumes:
    #   - ./mongodb_data_container:/data/db
    networks:
      net:
        aliases:
          - mongo

  spring-native-crud-mongodb:
    image: fielcapao/spring-native-crud-mongodb-amd64 #To run local version use spring-native-crud-mongodb:0.0.1-SNAPSHOT
    container_name: spring-native-crud-mongodb
    ports:
      - 8080:8080
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
    networks:
      net:
        aliases:
          - spring-native-crud-mongodb

networks:
  net: