# This is a basic workflow to help you get started with Actions

name: Spring Native - Build docker image for AMD64 and AARCH64

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: contains(toJson(github), 'build docker-image')
    name: Build and Publish Docker images to DockerHub

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Set up JDK 11
      - name: JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Graalvm(amd64)
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '21.0.0.2.java11'
#          args: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0.2/graalvm-ce-java11-linux-amd64-21.0.0.2.tar.gz

      - name: Install native-image component(amd64)
        run: |
          gu install native-image

      # Build the Docker image with Maven
      - name: Build Docker Image(amd64)
        run: |
           mvn clean install spring-boot:build-image -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      # Login to Dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push the Docker image amd64
      - name: Push
        run: |
          docker tag spring-native-crud-mongodb:0.0.1-SNAPSHOT fielcapao/spring-native-crud-mongodb-amd64
          docker push fielcapao/spring-native-crud-mongodb-amd64

      - name: Setup Graalvm(aarch64)
        uses: rtc11/setup-graalvm@master
        with:
          args: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0.2/graalvm-ce-java11-linux-aarch64-21.0.0.2.tar.gz

      # Run commands on aarch64
      - name: Run on aarch64
        uses: uraimo/run-on-arch-action@v2.0.9
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)

      - name: Install native-image component(aarch64)
        run: |
          sudo chmod -R a+rwx graalvm/
#          graalvm/bin/gu install native-image
#          graalvm/bin/native-image --version

      # Build the Docker image with Maven
      - name: Build Docker Image(aarch64)
        run: |
           mvn clean install docker:build -DskipTests -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      # Push the Docker image aarch64
      - name: Push
        run: |
          docker tag spring-native-crud-mongodb:0.0.1-SNAPSHOT fielcapao/spring-native-crud-mongodb-aarch64
          docker push fielcapao/spring-native-crud-mongodb-aarch64
